# Generated by Django 3.0.14 on 2022-08-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='nickname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
