# Generated by Django 3.0.14 on 2022-08-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220801_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_Premium',
            field=models.BooleanField(default=False),
        ),
    ]
