# Generated by Django 3.2 on 2022-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='shop_runtime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
