# Generated by Django 3.0.14 on 2022-07-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220725_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
