# Generated by Django 3.0.14 on 2022-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220725_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qrcode',
        ),
    ]
