# Generated by Django 3.0.14 on 2022-08-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220803_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='media/default_img.png', upload_to='profile_img'),
        ),
    ]
