# Generated by Django 3.0.14 on 2022-07-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='url',
        ),
    ]
