# Generated by Django 3.0.14 on 2022-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='qrcode'),
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
