# Generated by Django 3.0.14 on 2022-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220725_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='shop_name',
        ),
    ]
