# Generated by Django 3.2 on 2022-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220814_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_bookmarked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
