# Generated by Django 3.0.14 on 2022-07-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customeruser_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='shop_phone_num',
            new_name='phone_num',
        ),
    ]
