# Generated by Django 3.2 on 2022-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_shopuser_is_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='is_bookmarked',
            field=models.BooleanField(null=True),
        ),
    ]
