# Generated by Django 3.2 on 2022-08-16 12:23

from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_star', models.IntegerField(default=3, validators=[shop.validators.validate_score])),
                ('review_photo', models.ImageField(blank=True, upload_to='')),
                ('review_caption', models.TextField(max_length=100)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_shopname', to='accounts.shopuser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_writer', to='accounts.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ShopQna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.review')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopuser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopuser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_num', models.IntegerField(blank=True, default=0)),
                ('stamp_num', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_shopname', to='accounts.shopuser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_writer', to='accounts.customeruser')),
            ],
        ),
    ]
