# Generated by Django 3.0.14 on 2022-07-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20220725_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_num', models.IntegerField(blank=True)),
                ('stamp_num', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_shopname', to='accounts.ShopUser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_writer', to='accounts.CustomerUser')),
            ],
        ),
    ]
