# Generated by Django 3.0.14 on 2022-08-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='seller',
            new_name='shopname',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='buyer',
            new_name='writer',
        ),
    ]
