# Generated by Django 3.2 on 2022-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
