# Generated by Django 3.0.14 on 2022-07-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220725_2230'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopQna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_star', models.IntegerField()),
                ('review_photo', models.ImageField(blank=True, upload_to='')),
                ('review_caption', models.TextField(max_length=100)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_shopname', to='accounts.ShopUser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_writer', to='accounts.CustomerUser')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomerUser')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ShopUser')),
            ],
        ),
    ]
