# Generated by Django 3.0.14 on 2022-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_payment_review_shopqna_shopquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='stamp_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.IntegerField(default=3),
        ),
    ]
