# Generated by Django 3.0.14 on 2022-08-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220801_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shopname',
            new_name='user',
        ),
    ]
