# Generated by Django 3.2 on 2022-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shop_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
