# Generated by Django 3.0.14 on 2022-08-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220801_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='shopname',
        ),
    ]
