# Generated by Django 3.2 on 2022-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220819_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cu_nickname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='cu_profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
