# Generated by Django 3.0.14 on 2022-08-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopuser_is_premium'),
        ('shop', '0006_auto_20220802_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ShopUser'),
        ),
    ]
