# Generated by Django 3.0.14 on 2022-08-02 04:32

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220802_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_comment',
            old_name='author',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.IntegerField(default=3, validators=[shop.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='review_comment',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
